version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "html-bundle-proxy-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cdwopih9y0ls"
s3_prefix = "html-bundle-proxy-app"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
