AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for deploy-react-app-with-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HtmlBundleProxyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: html_bundle_proxy/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Index:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
        AnyPath:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{path+}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HtmlBundleProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for HTML Proxy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HtmlBundleProxyFunction:
    Description: "HTML Proxy Lambda Function ARN"
    Value: !GetAtt HtmlBundleProxyFunction.Arn
  HtmlBundleProxyFunctionLogGroupName:
    Description: "HTML Proxy Lambda Function LogGroup Name"
    Value: !Join [ "/", ["aws", "lambda", !Ref HtmlBundleProxyFunction]]

  HtmlBundleProxyFunctionIamRole:
    Description: "Implicit IAM Role created for HTML Proxy function"
    Value: !GetAtt HtmlBundleProxyFunctionRole.Arn
